//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OneCenter.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class OneCenterEntities : DbContext
    {
        public OneCenterEntities()
            : base("name=OneCenterEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Activity> Activity { get; set; }
        public virtual DbSet<ActivityRecord> ActivityRecord { get; set; }
        public virtual DbSet<Admin> Admin { get; set; }
        public virtual DbSet<Member> Member { get; set; }
        public virtual DbSet<ProductRecord> ProductRecord { get; set; }
        public virtual DbSet<Schedule> Schedule { get; set; }
        public virtual DbSet<Set> Set { get; set; }
        public virtual DbSet<SetDetail> SetDetail { get; set; }
        public virtual DbSet<Ticket> Ticket { get; set; }
        public virtual DbSet<TicketRecord> TicketRecord { get; set; }
    }
}
