//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OneCenter.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TicketRecord
    {
        public int Id { get; set; }
        public int MemberId { get; set; }
        public int TicketId { get; set; }
        public Nullable<int> ActivityId { get; set; }
        public Nullable<int> SetId { get; set; }
        public short Type { get; set; }
        public Nullable<System.DateTime> UsedDate { get; set; }
        public System.DateTime CreateDate { get; set; }
        public System.DateTime UpdateDate { get; set; }
    
        public virtual Activity Activity { get; set; }
        public virtual Member Member { get; set; }
        public virtual Set Set { get; set; }
        public virtual Ticket Ticket { get; set; }
    }
}
